namespace Soenneker.Quark;

public sealed class QuarkPresetContext
{
    public string? Class { get; set; }
    public CssValue<InsetBuilder>? Inset { get; set; }
    public CssValue<DisplayBuilder>? Display { get; set; }
    public CssValue<VisibilityBuilder>? Visibility { get; set; }
    public CssValue<FloatBuilder>? Float { get; set; }
    public CssValue<VerticalAlignBuilder>? VerticalAlign { get; set; }
    public CssValue<TextAlignBuilder>? TextAlign { get; set; }
    public CssValue<TextColorBuilder>? TextColor { get; set; }
    public CssValue<TextSizeBuilder>? TextSize { get; set; }
    public CssValue<DecorationLineBuilder>? DecorationLine { get; set; }
    public CssValue<TextTransformBuilder>? TextTransform { get; set; }
    public CssValue<FontFamilyBuilder>? FontFamily { get; set; }
    public CssValue<FontWeightBuilder>? FontWeight { get; set; }
    public CssValue<FontStyleBuilder>? FontStyle { get; set; }
    public CssValue<LeadingBuilder>? Leading { get; set; }
    public CssValue<TrackingBuilder>? Tracking { get; set; }
    public CssValue<WhitespaceBuilder>? Whitespace { get; set; }
    public CssValue<TextWrapBuilder>? TextWrap { get; set; }
    public CssValue<TextBreakBuilder>? TextBreak { get; set; }
    public CssValue<TextOverflowBuilder>? TextOverflow { get; set; }
    public CssValue<TruncateBuilder>? Truncate { get; set; }
    public CssValue<LineClampBuilder>? LineClamp { get; set; }
    public CssValue<FontVariantNumericBuilder>? FontVariantNumeric { get; set; }
    public CssValue<MarginBuilder>? Margin { get; set; }
    public CssValue<PaddingBuilder>? Padding { get; set; }
    public CssValue<PositionBuilder>? Position { get; set; }
    public CssValue<ScrollMarginBuilder>? ScrollMargin { get; set; }
    public CssValue<SizeBuilder>? BoxSize { get; set; }
    public CssValue<WidthBuilder>? Width { get; set; }
    public CssValue<MinWidthBuilder>? MinWidth { get; set; }
    public CssValue<MaxWidthBuilder>? MaxWidth { get; set; }
    public CssValue<HeightBuilder>? Height { get; set; }
    public CssValue<HeightBuilder>? MinHeight { get; set; }
    public CssValue<HeightBuilder>? MaxHeight { get; set; }
    public CssValue<OverflowBuilder>? Overflow { get; set; }
    public CssValue<OverflowBuilder>? OverflowX { get; set; }
    public CssValue<OverflowBuilder>? OverflowY { get; set; }
    public CssValue<OverscrollBuilder>? Overscroll { get; set; }
    public CssValue<FlexBuilder>? Flex { get; set; }
    public CssValue<FlexDirectionBuilder>? FlexDirection { get; set; }
    public CssValue<FlexWrapBuilder>? FlexWrap { get; set; }
    public CssValue<GrowBuilder>? Grow { get; set; }
    public CssValue<ShrinkBuilder>? Shrink { get; set; }
    public CssValue<GapBuilder>? Gap { get; set; }
    public CssValue<SpaceBuilder>? Space { get; set; }
    public CssValue<DivideBuilder>? Divide { get; set; }
    public CssValue<ContentAlignBuilder>? ContentAlign { get; set; }
    public CssValue<ItemsBuilder>? ItemsAlign { get; set; }
    public CssValue<JustifyBuilder>? Justify { get; set; }
    public CssValue<SelfBuilder>? SelfAlign { get; set; }
    public CssValue<JustifyItemsAlignBuilder>? JustifyItemsAlign { get; set; }
    public CssValue<JustifySelfAlignBuilder>? JustifySelfAlign { get; set; }
    public CssValue<OpacityBuilder>? Opacity { get; set; }
    public CssValue<ZIndexBuilder>? ZIndex { get; set; }
    public CssValue<PointerEventsBuilder>? PointerEvents { get; set; }
    public CssValue<UserSelectBuilder>? UserSelect { get; set; }
    public CssValue<CursorBuilder>? Cursor { get; set; }
    public CssValue<ScreenReaderBuilder>? ScreenReader { get; set; }
    public CssValue<BackgroundColorBuilder>? BackgroundColor { get; set; }
    public CssValue<BorderColorBuilder>? BorderColor { get; set; }
    public CssValue<BorderBuilder>? Border { get; set; }
    public CssValue<RoundedBuilder>? Rounded { get; set; }
    public CssValue<RingColorBuilder>? RingColor { get; set; }
    public CssValue<RingBuilder>? Ring { get; set; }
    public CssValue<BoxShadowBuilder>? BoxShadow { get; set; }
    public CssValue<BackdropFilterBuilder>? BackdropFilter { get; set; }
    public CssValue<FilterBuilder>? Filter { get; set; }
    public CssValue<ResizeBuilder>? Resize { get; set; }
    public CssValue<TransformBuilder>? Transform { get; set; }
    public CssValue<AnimationBuilder>? Animation { get; set; }
    public CssValue<TransitionBuilder>? Transition { get; set; }
}
