using System.Collections.Generic;

namespace Soenneker.Quark.Suite.Demo;

public static class DocsNavigation
{
    private static string ComponentRoute(string route) => $"components/{route.Trim('/')}";

    public static IReadOnlyList<NavigationItem> TopLinks { get; } =
    [
        new("Docs", ".", ExactMatch: true),
        new("Components", "components")
    ];

    public static IReadOnlyList<NavigationItem> SectionLinks { get; } =
    [
        new("Introduction", "introduction"),
        new("Components", "components"),
        new("Installation", "installation"),
        new("Properties", "properties"),
        new("Grid System", "grid-system"),
        new("Themes", "themes"),
        new("Validation", ComponentRoute("validation"))
    ];

    public static IReadOnlyList<NavigationItem> ComponentLinks { get; } =
    [
        new("Accordion", ComponentRoute("accordion")),
        new("Alert", ComponentRoute("alert")),
        new("Alert Dialog", ComponentRoute("alert-dialog")),
        new("Announcement", ComponentRoute("announcement")),
        new("Aspect Ratio", ComponentRoute("aspect-ratio")),
        new("Attachments", ComponentRoute("attachments")),
        new("Avatar", ComponentRoute("avatar")),
        new("Autosave", ComponentRoute("autosave")),
        new("Badge", ComponentRoute("badge")),
        new("Breadcrumb", ComponentRoute("breadcrumb")),
        new("Button", ComponentRoute("button")),
        new("Button Group", ComponentRoute("button-group")),
        new("Calendar", ComponentRoute("calendar")),
        new("Card", ComponentRoute("card")),
        new("Carousel", ComponentRoute("carousel")),
        new("Chart", ComponentRoute("charts"), IsNew: true),
        new("Payment Card", ComponentRoute("payment-card")),
        new("Cascader", ComponentRoute("cascader")),
        new("Chain of Thought", ComponentRoute("chain-of-thought")),
        new("Checkbox", ComponentRoute("checkbox")),
        new("Citation", ComponentRoute("citation")),
        new("Cloudflare AI Search", ComponentRoute("cloudflare-ai-search"), IsNew: true),
        new("CodeEditor", ComponentRoute("codeeditors")),
        new("Collapsible", ComponentRoute("collapsible")),
        new("Color Picker", ComponentRoute("color-picker")),
        new("Combobox", ComponentRoute("combobox")),
        new("Command", ComponentRoute("command")),
        new("ConsolePanel", ComponentRoute("console-panel"), IsNew: true),
        new("Consent Manager", ComponentRoute("consent-manager")),
        new("Container", ComponentRoute("container")),
        new("Context Menu", ComponentRoute("context-menu")),
        new("Copy Button", ComponentRoute("copy-button")),
        new("Copy Field", ComponentRoute("copy-field")),
        new("Copyable Text", ComponentRoute("copyable-text")),
        new("Currency Input", ComponentRoute("currency-inputs")),
        new("DataTable", ComponentRoute("datatables")),
        new("Date Time", ComponentRoute("date-time")),
        new("Date Picker", ComponentRoute("date-picker")),
        new("Dialog", ComponentRoute("dialog")),
        new("Direction", ComponentRoute("direction")),
        new("Drawer", ComponentRoute("drawer")),
        new("Dropdown Menu", ComponentRoute("dropdown-menu")),
        new("Empty", ComponentRoute("empty")),
        new("Feedback Bar", ComponentRoute("feedback-bar")),
        new("Field", ComponentRoute("field")),
        new("Floating Window", ComponentRoute("floating-window")),
        new("Grid", ComponentRoute("grids")),
        new("Header", ComponentRoute("headers")),
        new("Hover Card", ComponentRoute("hover-card")),
        new("Image", ComponentRoute("images")),
        new("Input", ComponentRoute("input")),
        new("Input Group", ComponentRoute("input-group")),
        new("Input OTP", ComponentRoute("input-otp")),
        new("Item", ComponentRoute("item")),
        new("Kanban", ComponentRoute("kanban")),
        new("Kbd", ComponentRoute("kbd")),
        new("Label", ComponentRoute("label")),
        new("Marquee", ComponentRoute("marquee")),
        new("Menubar", ComponentRoute("menubar")),
        new("Message", ComponentRoute("message")),
        new("Model Selector", ComponentRoute("model-selectors")),
        new("Native Dialog", ComponentRoute("native-dialog"), IsNew: true),
        new("Native Select", ComponentRoute("native-select")),
        new("Navigation Menu", ComponentRoute("navigation-menu")),
        new("Node Editor", ComponentRoute("node-editor")),
        new("On This Page", ComponentRoute("docs-on-this-page")),
        new("Pagination", ComponentRoute("pagination")),
        new("Password Input", ComponentRoute("password-input")),
        new("Pill", ComponentRoute("pill")),
        new("Popover", ComponentRoute("popover")),
        new("Progress", ComponentRoute("progress")),
        new("Prompt Input", ComponentRoute("prompt-inputs")),
        new("Questionnaire", ComponentRoute("questionnaire"), IsNew: true),
        new("Radio Group", ComponentRoute("radio-group")),
        new("Reasoning", ComponentRoute("reasoning")),
        new("Resizable", ComponentRoute("resizable")),
        new("Score", ComponentRoute("scores")),
        new("Scroll Area", ComponentRoute("scroll-area")),
        new("Scroll Reveal", ComponentRoute("scroll-reveal")),
        new("Select", ComponentRoute("select")),
        new("Separator", ComponentRoute("separator")),
        new("Sheet", ComponentRoute("sheet")),
        new("Sidebar", ComponentRoute("sidebar")),
        new("Signature Pad", ComponentRoute("signature-pad")),
        new("Skeleton", ComponentRoute("skeleton")),
        new("Slider", ComponentRoute("slider")),
        new("Sonner", ComponentRoute("sonner")),
        new("Sortable", ComponentRoute("sortables")),
        new("Spinner", ComponentRoute("spinner")),
        new("Stack", ComponentRoute("stack")),
        new("Stepper", ComponentRoute("stepper")),
        new("Suggestions", ComponentRoute("suggestions")),
        new("Switch", ComponentRoute("switch")),
        new("Table", ComponentRoute("table")),
        new("Tabs", ComponentRoute("tabs")),
        new("Tag Input", ComponentRoute("tag-input")),
        new("Text Shimmer", ComponentRoute("text-shimmer")),
        new("Textarea", ComponentRoute("textarea")),
        new("Theme Toggle Button", ComponentRoute("theme-toggle-button")),
        new("Thread", ComponentRoute("threads")),
        new("Timeline", ComponentRoute("timelines")),
        new("Toast", ComponentRoute("toast")),
        new("Toggle", ComponentRoute("toggle")),
        new("Toggle Group", ComponentRoute("toggle-groups")),
        new("Tooltip", ComponentRoute("tooltip")),
        new("Typography", ComponentRoute("typography"))
    ];

    public static IReadOnlyList<NavigationItem> PrimitiveLinks { get; } =
    [
        new("Anchor", ComponentRoute("anchors")),
        new("Aside", ComponentRoute("asides")),
        new("Blockquote", ComponentRoute("blockquotes")),
        new("Br", ComponentRoute("br")),
        new("Code", ComponentRoute("codes")),
        new("Div", ComponentRoute("divs")),
        new("Fieldset", ComponentRoute("fieldsets")),
        new("Figure", ComponentRoute("figures")),
        new("Icons", ComponentRoute("icons")),
        new("Margin", ComponentRoute("margins")),
        new("Nav", ComponentRoute("navs")),
        new("Padding", ComponentRoute("padding")),
        new("Paragraph", ComponentRoute("paragraphs")),
        new("Section", ComponentRoute("sections")),
        new("Semantic HTML", ComponentRoute("semantic-html")),
        new("Simple Icons", ComponentRoute("simple-icons")),
        new("Small", ComponentRoute("small")),
        new("Span", ComponentRoute("spans")),
        new("Strong", ComponentRoute("strong")),
        new("Svg", ComponentRoute("svgs")),
        new("Text", ComponentRoute("texts"))
    ];
}
